name: Vérification du respect des spécifications

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Installation des dépendances
      run: pip install -r requirements.txt
    - name: Vérification du schéma lave-linge et des fichiers d'exemples associés
      run: |
        frictionless validate --type schema lave-linge/schema.json
        frictionless validate --schema lave-linge/schema.json lave-linge/exemple-valide.csv
    - name: Vérification du schéma televiseur et des fichiers d'exemples associés
      run: |
        frictionless validate --type schema televiseur/schema.json
        frictionless validate --schema televiseur/schema.json televiseur/exemple-valide.csv
    - name: Vérification du datapackage
      run: |
        frictionless validate datapackage.json